blueprint:
  name: "ðŸŽ™ï¸ Alexa: Dreame Room Cleaning Scripts"
  description: |
    ## ðŸš€ What this blueprint does
    Creates a **custom script** to control your Dreame robot with voice commands via Alexa!
    
    âœ… **Targeted cleaning** of a specific room  
    âœ… **4 cleaning modes** available  
    âœ… **Alexa ready** - no additional configuration needed  
    âœ… **Easily clonable** for multiple rooms  
    
    ## ðŸ  Available Cleaning Modes
    
    | **Mode** | **Description** | **Technology** |
    |:---:|:---:|:---:|
    | ðŸ§¹ **Vacuum** | Vacuum only | Custom Cleaning |
    | ðŸ’§ **Mop** | Mop only | Custom Cleaning |
    | âœ¨ **Cleaning** | Vacuum + Mop | CleanGenius |
    | ðŸ”¥ **Deep Cleaning** | Vacuum + Intensive Mop | CleanGenius Deep |
    
    ## ðŸ“‹ Prerequisites
    1. âœ… Dreame robot configured in Home Assistant
    2. âœ… Room helper created (use the "ðŸ  Room Helper Creation" blueprint)
    3. âœ… Alexa configured (Nabu Casa, Lambda, or Matter)
    
    ## ðŸŽ¯ How to Use It
    
    ### Step 1: Configure the Script
    1. **Select** your robot and required entities
    2. **Enter** the room ID (find it in your room helper)
    3. **Choose** the cleaning mode
    4. **Save** the script with a descriptive name
    
    ### Step 2: Expose to Alexa
    - **Nabu Casa**: Script will appear automatically
    - **Matter**: Add "matter" label to the script
    - **Lambda**: Configure in your AWS setup
    
    ### Step 3: Voice Commands
    **"Alexa, start [script name]"**  
    **"Alexa, open [script name]"**
    
    ## ðŸ’¡ Practical Examples
    
    ### Scenario: Bathroom Cleaning
    1. **Create** script: "Vacuum Bathroom" (Room ID: 5, Mode: Vacuum)
    2. **Clone** script: "Clean Bathroom" (same ID, Mode: Cleaning)
    3. **Commands**: 
       - "Alexa, start vacuum bathroom" 
       - "Alexa, start clean bathroom"
    
    ### Scenario: Complete Kitchen
    - Script 1: "Clean Kitchen" â†’ "Alexa, start clean kitchen"
    - Script 2: "Deep Clean Kitchen" â†’ "Alexa, start deep clean kitchen"
    
    ## âš™ï¸ Technical Notes
    - **CleanGenius**: Advanced mode that combines vacuuming and mopping
    - **Custom Cleaning**: Basic mode for separate vacuuming or mopping
    - **Timeout**: 10 seconds for setting changes
    - **Validation**: Automatically checks that room ID is valid
    
  domain: script
  source_url: https://raw.githubusercontent.com/Magnum9O/HA_BluePrints/main/Dreame/ENG/2_ExposeToAlexa.yaml

  input:
    vacuum_entity:
      name: "ðŸ¤– Dreame Robot"
      description: |
        Select your Dreame robot vacuum cleaner.
        
        ðŸ’¡ **Example**: `vacuum.dreame_l10s_ultra` or `vacuum.xiaomi_vacuum_cleaner`
      selector:
        entity:
          domain: vacuum

    cleangenius_select:
      name: "âœ¨ CleanGenius Entity"
      description: |
        Select the entity that controls your robot's **CleanGenius** mode.
        
        ðŸ’¡ **How to find it**: Look among your robot's `select` entities, usually named:
        - `select.robot_name_cleangenius`
        - `select.dreame_cleangenius`
      selector:
        entity:
          domain: select

    cleaning_mode_select:
      name: "ðŸ”§ Cleaning Mode Entity"
      description: |
        Select the entity that controls **Cleaning Mode** (separate vacuum/mop).
        
        ðŸ’¡ **How to find it**: Look among your robot's `select` entities, usually:
        - `select.robot_name_cleaning_mode`
        - `select.dreame_cleaning_mode`
      selector:
        entity:
          domain: select

    room_id:
      name: "ðŸ  Room ID"
      description: |
        **Enter the numeric ID** of the room you want to clean.
        
        ðŸ” **How to find it**: 
        1. Use the "ðŸ  Room Helper Creation" blueprint
        2. Check the created helper to see "Room Name (**ID**)"
        3. Enter only the number in parentheses
        
        ðŸ“ **Example**: If you see "Kitchen (3)", enter **3**
      selector:
        number:
          min: 0
          max: 999
          mode: box
      default: 0

    cleaning_preset:
      name: "ðŸŽ¯ Cleaning Mode"
      description: |
        Choose your desired cleaning mode:
        
        ðŸ§¹ **Vacuum**: Vacuum only (CleanGenius OFF)
        ðŸ’§ **Mop**: Mop only (CleanGenius OFF)  
        âœ¨ **Cleaning**: Vacuum + Mop simultaneously
        ðŸ”¥ **Deep Cleaning**: Vacuum + Intensive Mop
      selector:
        select:
          options:
            - label: "ðŸ§¹ Vacuum"
              value: "Vacuum"
            - label: "ðŸ’§ Mop" 
              value: "Mop"
            - label: "âœ¨ Cleaning"
              value: "Cleaning"
            - label: "ðŸ”¥ Deep Cleaning"
              value: "Deep Cleaning"
      default: "Cleaning"

icon: mdi:robot-vacuum

mode: single

sequence:
  - variables:
      _vac: !input vacuum_entity
      _cg_sel: !input cleangenius_select
      _cm_sel: !input cleaning_mode_select
      _rid: !input room_id
      _preset_raw: !input cleaning_preset
      preset: "{{ (_preset_raw or 'Cleaning') | lower }}"

  # Validate room ID
  - condition: template
    value_template: "{{ (_rid | int(default=-1)) >= 0 }}"
    alias: "Verify room ID validity"

  # Branch based on preset
  - choose:
      # DEEP CLEANING â†’ CleanGenius deep_cleaning
      - conditions:
          - condition: template
            value_template: "{{ preset == 'deep cleaning' }}"
        sequence:
          - alias: "Set CleanGenius Deep Cleaning"
            service: select.select_option
            target:
              entity_id: "{{ _cg_sel }}"
            data:
              option: deep_cleaning

          - alias: "Wait for CleanGenius mode change"
            wait_template: >-
              {{ states(_cg_sel) in ['deep_cleaning','unknown','unavailable','none'] }}
            timeout: "00:00:10"

          - alias: "Start deep cleaning room"
            service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vac }}"
            data:
              segments:
                - "{{ _rid | int }}"

      # CLEANING (standard) â†’ CleanGenius left as-is (no change), then start
      - conditions:
          - condition: template
            value_template: "{{ preset == 'cleaning' }}"
        sequence:
          - alias: "Start standard cleaning room"
            service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vac }}"
            data:
              segments:
                - "{{ _rid | int }}"

      # VACUUM â†’ CleanGenius OFF â†’ cleaning_mode sweeping â†’ start
      - conditions:
          - condition: template
            value_template: "{{ preset == 'vacuum' }}"
        sequence:
          - alias: "Disable CleanGenius"
            service: select.select_option
            target:
              entity_id: "{{ _cg_sel }}"
            data:
              option: 'off'

          - alias: "Wait for CleanGenius disable"
            wait_template: >-
              {{ states(_cg_sel) in ['off','unknown','unavailable','none'] }}
            timeout: "00:00:10"

          - alias: "Set vacuum mode"
            service: select.select_option
            target:
              entity_id: "{{ _cm_sel }}"
            data:
              option: sweeping

          - delay: "00:00:01"

          - alias: "Start vacuum room"
            service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vac }}"
            data:
              segments:
                - "{{ _rid | int }}"

      # MOP â†’ CleanGenius OFF â†’ cleaning_mode mopping â†’ start
      - conditions:
          - condition: template
            value_template: "{{ preset == 'mop' }}"
        sequence:
          - alias: "Disable CleanGenius"
            service: select.select_option
            target:
              entity_id: "{{ _cg_sel }}"
            data:
              option: 'off'

          - alias: "Wait for CleanGenius disable"
            wait_template: >-
              {{ states(_cg_sel) in ['off','unknown','unavailable','none'] }}
            timeout: "00:00:10"

          - alias: "Set mop mode"
            service: select.select_option
            target:
              entity_id: "{{ _cm_sel }}"
            data:
              option: mopping

          - delay: "00:00:01"

          - alias: "Start mop room"
            service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vac }}"
            data:
              segments:
                - "{{ _rid | int }}"

    default: []